[providers]
node = "18.x"

[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["cd backend", "npm ci --only=production"]

[phases.build]
cmds = ["cd backend", "echo 'Build completed'"]

[start]
cmd = "cd backend && node server.js"