services:
  - type: web
    name: stepup-cloud-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: stepup-cloud-db
          property: connectionString
    
databases:
  - name: stepup-cloud-db
    databaseName: stepup_cloud
    plan: free