name: Deploy Frontend to GitHub Pages and Backend to Render

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Build with production API URL
      run: |
        cd frontend
        export REACT_APP_API_URL="https://stepup-cloud-backend.onrender.com"
        npm run build
        
    - name: Add custom domain and 404 handling
      run: |
        echo "aebonlee.github.io" > ./frontend/build/CNAME
        cp ./frontend/build/index.html ./frontend/build/404.html
        
    - name: Copy to docs folder for GitHub Pages
      run: |
        rm -rf docs
        cp -r ./frontend/build docs
        
    - name: Commit and push to main branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs
        git commit -m "🚀 Deploy: Update GitHub Pages (docs folder)" -a || echo "No changes to commit"
        git push

  deploy-backend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}