name: Deploy Frontend to GitHub Pages and Backend to Railway

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Build with production API URL
      run: |
        cd frontend
        export REACT_APP_API_URL="https://stepup-cloud-backend.up.railway.app"
        npm run build
        
    - name: Add custom domain and 404 handling
      run: |
        echo "aebonlee.github.io" > ./frontend/build/CNAME
        cp ./frontend/build/index.html ./frontend/build/404.html
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./frontend/build
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

  deploy-backend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && vars.ENABLE_RAILWAY_DEPLOY == 'true'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Deploy to Railway
      uses: railwayapp/railway-deploy@v1.0.8
      with:
        service: stepup-cloud-backend
        railway_token: ${{ secrets.RAILWAY_TOKEN }}